added retry fuctionality for health check

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -67,8 +67,15 @@ jobs:
 
             echo "Waiting for application to start..."
 
-            sleep 10
+            for i in {1..30}; do
+              if curl --fail http://localhost:9091/actuator/health; then
+                echo "Application is healthy"
+                exit 0
+            fi
 
-            echo "Checking application health..."
-
-            curl --fail http://localhost:9091/actuator/health
+            echo "Waiting for application..."
+            sleep 2
+            done
+  
+           echo "Application failed to become healthy"
+           exit 1
